sass:
    sass_dir: _sass
    style: compressed    

plugins:
  - jekyll-autoprefixer    

collections:
  posts:
    output: true
    permalink: /:categories/:title:output_ext

staticman_url: https://invertirenfondos-comments.herokuapp.com/v3/entry/github/PabloPerez/invertirenfondos/main/comments

reCaptcha:
  siteKey: 6LdWtpIaAAAAAOjR4pkpuiCl5gdP9Lev2GttkRkv
