sass:
    sass_dir: _sass
    style: compressed    

plugins:
  - jekyll-autoprefixer    

collections:
  posts:
    output: true
    permalink: /:categories/:title:output_ext

staticman_url: https://invertirenfondos-comments.herokuapp.com/v3/entry/github/PabloPerez/invertirenfondos/main/comments

reCaptcha:
  siteKey: 6LdWtpIaAAAAAOjR4pkpuiCl5gdP9Lev2GttkRkv
  secret: H1QTOvPrR9llsN7Sfz10fCI+gYwbu9VUsQOB1cYPgXBBjNlodanra4Fw3PZjRmo9QIezMqsGwsaucK9ctjWuREfsDhfdM4uko1cUgsMmxmutqlpYKzdByrIkW0/G6MwZTQv5z/2MQhebtZIIbhE33HUWorLGv46JfLJerqVST6Jh3Hhvhss6/hTg1igAww+9bN7UwuQOoYvP0ZPGDWrTDonghdmjJRU/+No3PVzoZhFvpLDVWePOt/EqrnnVId7v139R4DPczXWczlpzQj3RjRZgXKbchpOFQwzm2HZ6GEZ3JWGU5jQUi6RoFbhnK04PR+HNTDUuAT3a0gbWyxy8Xy08BOerAyRWYRIp/lj/BR6VXs3DbmP2HFOxqDrz+ZFKE/ZXqj41Bne9PTULmVm50ZMhiD16/hKarnP3JqMcm9EcNqNJ2L/ZJXJ/dGMQ7HWCUXzeSwYFGsy+sQ1I3yk/K75LCtTcCuyjuAvk4/xwSrz7/dwbTfZJZoIijhuCZbYXe747njTNI9HSfA4rHUT+N4v1k2AYMz6MD5+GBKKNiaM5tsR6MwTPF4brKQRM0G/GLVqiVvhVHl+NeAQzu2U+sGhpp8hZhSVq8nzpIjObyfNHhOCxuNP2jjGMXBStuacH5+nwRoQOmJc8VE1lAQPc4W6dRvY2RHKgmTBOn4KAZZw=

logoImage: https://www.invertirenfondos.info/assets/images/logo_large.png

lastQuarter: 2020T4

version: v1.0.1